### ISSUE TITLE
can't create a pull request trying to contribute

### ISSUE THREAD

**Issue by ohadpartuck** [sensu/sensu-community-plugins#1005]
```
/sensu-community-plugins (rabbit_messges_each_queue) git push origin rabbit_messges_each_queue
ERROR: Permission to sensu/sensu-community-plugins.git denied to ohadpartuck.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mattyjones** [comment]
@ohadpartuck You are trying to push directly to the project repo, if you like to contribute you will need to fork the project repo to your own account, make the changes and push them to yourself first.

When you have done this you can create a Pull Request across the two repos for the team to take a look at.  Any further questions drop me a line.

**Comment by ohadpartuck** [comment]
10x, @mattyjones . https://github.com/sensu/sensu-community-plugins/pull/1009/files, done.
