### ISSUE TITLE
Sensu Sidekiq Check

### ISSUE THREAD

**Issue by imkarthikk** [sensu/sensu-community-plugins#1008]
Sorry if I'm posting this in a wrong place. But just wanted to check if there are any existing Checks and Plugins for monitoring Sidekiq. We use Sidekiq extensively to handle our background jobs, and monitoring it with Graphite with Sensu is not possible at the moment (I think).

**Comment by mattyjones** [comment]
@imkarthikk There is nothing currently existing at the moment that I am aware of here.  It could be that someone else has written something and not submitted it though.  If you have the time and want to write something I would be more than happy to take a look at it.
