### ISSUE TITLE
check-elb-certs.rb doesn't work with embedded ruby 2.0.0p353

### ISSUE THREAD

**Issue by scaissie** [sensu/sensu-community-plugins#1018]
ubuntu@ip-10-0-1-157:~$ /opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-elb-certs.rb -a <REDACTED> -s <REDACTED> -r us-east-1 -w 60 -c 30
Check failed to run: uninitialized constant CheckELBCerts::AWS, ["/etc/sensu/plugins/check-elb-certs.rb:88:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
ubuntu@ip-10-0-1-157:~$ /opt/sensu/embedded/bin/ruby --version
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]

It looks like aws-sdk no longer supports memoizing

**Comment by mattyjones** [comment]
@scaissie  You posted your aws creds in the original issue, I edited the issue but you should change them ASAP.

**Comment by scaissie** [comment]
Yikes! Thanks for catching that.

**Comment by mattyjones** [comment]
@scaissie @nathwill It is worth mentioning that in the next version of the [aws gem](https://rubygems.org/gems/sensu-plugins-aws) you will not be able to specifiy tokens or creds from the command line.  They will be treated liked ssh keys and may only be read in from a properly secured local file.

In fact as the gems get released at any point where I find code like that it will be pulled and the user will be forced to use a local file, databag, etc.  The less places those creds have to see the light of day the better.  For an example check out [GIR](https://github.com/sensu-plugins/GIR/blob/master/config/rake.rb) and how I treat the github token

```ruby
def acquire_git_token
  File.readlines(File.expand_path('~/.ssh/git_token')).each do |line|
    return line
  end
end
```

**Comment by brandoconnor** [comment]
Having a similar issue with the AWS SNS handler. Looking at the [current documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html) for the aws-sdk gem, the interface must have changed as a new client is now created with:
`sns = Aws::SNS::Client.new(
  region: region_name,
  credentials: credentials
)`
and would publish using:
`resp = sns.publish(
  topic_arn: "topicARN",
  target_arn: "String",
  # required
  message: "message",
  subject: "subject",
  message_structure: "messageStructure",
  message_attributes: {
    "String" => {
      # required
      data_type: "String",
      string_value: "String",
      binary_value: "Binary<String,IO>",
    },
  },
)`
sns.rb currently does the following to create a client:
`sns = AWS::SNS.new`
at which point it thows:
`Exception occured in SnsNotifier: uninitialized constant SnsNotifier::AWS`
I'll look to fix up the SNS portion tomorrow and submit a pull request when that's working.

**Comment by mattyjones** [comment]
@brandoconnor  can you look [here][https://github.com/sensu-plugins/sensu-plugins-aws] before submitting a request please.  We are currently doing a major rewrite of the AWS stuff.

**Comment by bkett** [comment]
@scaissie Memoization is still supported in v1 of the aws-sdk gem. For the first part of the rewrite we will continue using v1 of the amazon ruby sdk. The gemspec in the upcoming gem will have a version of the aws-sdk gem specified at 1.x (1.63 as of this writing) and so the memoization issue should not persist.

I suppose I've dove into more info than you were looking for, but I suspect you can solve this issue by downgrading your aws-sdk gem from version 2 to 1.63.0. 

@brandoconnor my fix also applies to your case, set the gem to be v1 and the issue should disappear.

**Comment by bkett** [comment]
I also want to note that Amazon has not posted a timeline for deprecation of aws-sdk-v1 and so you should not worry about checks becoming defunct in the near future.

**Comment by bkett** [comment]
@mattyjones I've made a PR to update the gem requirement: see https://github.com/sensu/sensu-community-plugins/pull/1047

**Comment by matthod** [comment]
What was the fix here? This is still happening with current version of plugin using aws-sdk-v1 gem. 

Check failed to run: undefined method `empty?' for 0:Fixnum, ["./check-elb-certs.rb:131:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
