### ISSUE TITLE
check-sensor.rb doesn't check IPMI sensors on local machine

### ISSUE THREAD

**Issue by ntesa** [sensu/sensu-community-plugins#1034]
It would be useful if check-sensor.rb would be able to check IPMI sensors on the local machine too.

**Comment by mrichar1** [comment]
I submitted a request to the rubyipmi module project to do this, since it currently only supports remote access. This is now being worked on for the 0.10.0 release: https://github.com/logicminds/rubyipmi/issues/24

Once this is done I plan to patch check-sensors.rb to support this.

**Comment by mattyjones** [comment]
When the time comes please open a PR at the new repo

https://github.com/sensu-plugins/sensu-plugins-ipmi

Thanks !
