### ISSUE TITLE
Contribution question: Where should new checks go?

### ISSUE THREAD

**Issue by rmc3** [sensu/sensu-community-plugins#1035]
A question on new contributions: Should new checks go here (sensu/sensu-community-plugins), to their respective sensu-plugins repo, or both?

**Comment by mattyjones** [comment]
They *should* go to both to be fair.  I am partial to them going to the new repos simply for the sake of it is easier for me but I will accept them in both locations.

Any refactoring, rewrites, or major functional changes will not be accepted into the community-plugins at this time without a good reason as it makes little sense IMHO, but I am always open to being overruled.

**Comment by rmc3** [comment]
Thanks for the clarification! Closing this issue.
