### ISSUE TITLE
Check-http.rb failed with incorrect header check on windows IIS system

### ISSUE THREAD

**Issue by sshah-biz** [sensu/sensu-community-plugins#1045]
We are using, Sensu 0.14 package and embedded ruby.
On our windows/IIS7 server, we are running the multiple sites with different headers. When we try to run the check with header match with embedded ruby like -" c:\opt\sensu\embedded\bin\ruby.exe C:\opt\sensu\plugins\windows\check-http.rb    -h 'l3vm250' -p '/ver1.0/utility/diagnostic' -H 'HOST:test.test.com' -P 80 -q 'test' -t 15" it failed with the "incorrect header check".

*BUT* when we run the test using the window curl executable ( curl -H "HOST:test.test.com" -X GET "http://172.27.128.57/ver1.0/utility/diagnostic") it works without any issue.

Any help to resolve this issue will be great favor.

Thank you,
Sanjay

**Comment by mattyjones** [comment]
@sshah-biz  Can you take a look at the plugins in the new repo

https://github.com/sensu-plugins/sensu-plugins-http and see if the issue persists.

Thanks
