### ISSUE TITLE
robocat destroyed ruby 1.8 compatibility

### ISSUE THREAD

**Issue by confiq** [sensu/sensu-community-plugins#1050]
[this commit](https://github.com/sensu/sensu-community-plugins/commit/7960d603f886b18a8a0f19bd75af928cb47bae95) destroyed option to use ruby1.8.

The question is, will we support 1.8 of ruby? Cause because of this commit there is almost not even one plugin that works.

**Comment by tas50** [comment]
It seems like with the EoL status of Ruby 1.8 combined with the omnibus install of Sensu that there's no real reason to support Ruby 1.8 at this point.

**Comment by mattyjones** [comment]
1.8 will not be supported.  If this is an issue I suggest you pull a pre-rubocop SHA and fork it.  This is a lot of work though, I would just suggest you use the embedded 2.0 Ruby unless you have good reason not to.

The plugins will maintain compatibility with only one EOL Ruby, in this case 1.9.3.

**Comment by confiq** [comment]
Even docs says there is no "offical support" for 1.8. I'm closing the issue
