### ISSUE TITLE
check-mailq.rb does not work with Ruby 1.8.7

### ISSUE THREAD

**Issue by teran-mckinney** [sensu/sensu-community-plugins#1061]
Hi Sensuians,

check-mailq.rb works great with 1.9.x for me, but on a CentOS 6.6 server it seems to be locked into Ruby 1.8.7. I do see a line to include rubygems if Ruby is older than 1.9, but that does not seem to be enough here.

```
$ /etc/sensu/conf.d/checks/check-mailq.rb
/etc/sensu/conf.d/checks/check-mailq.rb:18: syntax error, unexpected ':', expecting kEND
         short: '-p MAILQ_PATH',
               ^
/etc/sensu/conf.d/checks/check-mailq.rb:18: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:19: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:20: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:24: syntax error, unexpected ':', expecting kEND
         short: '-w WARN_NUM',
               ^
/etc/sensu/conf.d/checks/check-mailq.rb:24: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:25: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:26: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:30: syntax error, unexpected ':', expecting kEND
         short: '-c CRIT_NUM',
               ^
/etc/sensu/conf.d/checks/check-mailq.rb:30: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:31: syntax error, unexpected ',', expecting kEND
/etc/sensu/conf.d/checks/check-mailq.rb:32: syntax error, unexpected ',', expecting kEND
```

Thanks,
Teran

**Comment by teran-mckinney** [comment]
I should probably link directly to the file in question: https://github.com/sensu/sensu-community-plugins/blob/master/plugins/postfix/check-mailq.rb

**Comment by wilshire461** [comment]
As a workaround you can in the file /etc/default/sensu set the EMBEDDED_RUBY variable to true if you would like your scripts to run with the prepackaged version of ruby that ships with sensu that also includes the sensu-plugin gem.
```
EMBEDDED_RUBY=true
```

**Comment by hurrycaine** [comment]
FYI I am getting same errors on plugins/check-procs.rb (RHEL6 System ruby 1.8.7)
@ wilshire461 that work around worked great.
Maybe EMBEDDED_RUBY=true should be the default and using system (or your own) ruby would be advanced? May be a good way of standardizing what ruby the plugins use and ease testing?

**Comment by mattyjones** [comment]
@hurrycaine I like the idea, I will add a not in the readme's or install docs(when we find them) that unless you know what you are doing, use the embedded ruby.

I use chef to manage my environments and when it creates a new user it can drop a user specific bashrc  and the user can specify aliases in their databag that will then will then get dropped into the chef run.  I myself have an alias that will set the embedded ruby for me.
