### ISSUE TITLE
Check whethere TCP/UDP port is reachable

### ISSUE THREAD

**Issue by lenfree** [sensu/sensu-community-plugins#1073]
Hi guys,

Do we have a check for this?

**Comment by mattyjones** [comment]
@lenfree I would modify the [check-banner](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/network/check-banner.rb) plugin or use it as is.

You could just write something that opens a socket to port N and if listening you are all set, or you could just do `telnet 0.0.0.0 -p N` inside a script as well.
