### ISSUE TITLE
mailer.rb Error

### ISSUE THREAD

**Issue by adithyakhamithkar** [sensu/sensu-community-plugins#1085]
Hi,

I have set up mailer.rb and mailer.json, specified all the necessary details. I am not able to receive emails, When I cheeked the logs seem to get getting this error in my sensu-server.log

{"timestamp":"2015-03-17T08:37:15.193886+0530","level":"info","message":"publishing check request","payload":{"name":"disk_check_root","issued":1426561635,"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-disk.rb -L /dev/xvda,/dev/sda,/dev/xvde,/dev/sde,/dev/vda -w 80 -c 85"},"subscribers":["ALL"]}
{"timestamp":"2015-03-17T08:37:15.313154+0530","level":"info","message":"handling event","event":{"id":"72deb574-5e02-4007-ae5f-5a1b235a77db","client":{"name":"web-01","address":"192.168.44.132","subscriptions":["ALL"],"safe_mode":true,"distribution":"Ubuntu","os_version":"trusty","version":"0.16.0","timestamp":1426561627},"check":{"handlers":["default"],"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-disk.rb -L /dev/xvda,/dev/sda,/dev/xvde,/dev/sde,/dev/vda -w 80 -c 85","interval":120,"subscribers":["ALL"],"name":"disk_check_root","issued":1426561635,"executed":1426561635,"duration":0.113,"output":"CheckDisk OK: All disk usage under 80%\n","status":0,"history":["0","0","0","0","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","0"]},"occurrences":16,"action":"resolve"},"handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/handlers/mailer.rb","name":"default"}}
{"timestamp":"2015-03-17T08:37:15.485121+0530","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/handlers/mailer.rb","name":"default"},"output":"/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- mail (LoadError)\n"}
{"timestamp":"2015-03-17T08:37:15.485833+0530","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/handlers/mailer.rb","name":"default"},"output":"\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'\n"}
{"timestamp":"2015-03-17T08:37:15.485948+0530","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/handlers/mailer.rb","name":"default"},"output":"\tfrom /etc/sensu/handlers/mailer.rb:19:in `<main>'\n"}
{"timestamp":"2015-03-17T08:37:15.486000+0530","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/handlers/mailer.rb","name":"default"},"output":"ignoring event -- no handler defined\n"}

Could someone please help me fix this issue.

**Comment by chrisduong** [comment]
I believe, you need to define sensu_gem 'mail'. Missing 'mail' gem

**Comment by thomaswsdyer** [comment]
@chrisduong, agreed.

@adithyakhamithkar you'll need to make sure the gem 'mail' is installed on your sensu-server.

    gem install mail

**Comment by adithyakhamithkar** [comment]
@chrisduong @thomaswsdyer 
Thanks I did dig deep into this I had the mail gem installed but, Sensu used using its embedded ruby version.
So I changed my check to use the embedded ruby.
