### ISSUE TITLE
check-memory-pcnt - Reporting memory usage incorrectly

### ISSUE THREAD

**Issue by NeckBeardPrince** [sensu/sensu-community-plugins#1090]
/check-memory-pcnt.sh -p
MEM CRITICAL - system memory usage: 36% | free memory=36MB;0;0;0

/etc/sensu/plugins# free -m
 total       used       free     shared    buffers     cached
Mem:          3951       2633       1317         33        193       1022
-/+ buffers/cache:       1417       2534
Swap:            0          0          0

**Comment by mattyjones** [comment]
There are several know issues with using free in new distro's.  It is being removed for use by the sensu-plugins.  Please check the new repos for updates @NeckBeardPrince 

https://github.com/sensu-plugins/sensu-plugins-memory-checks
