### ISSUE TITLE
cannot install postgres-metric dependency `pg` using embedded `gem` (checking for PQconnectdb() in -lpq... no)

### ISSUE THREAD

**Issue by mhalligan** [sensu/sensu-community-plugins#1101]
First off, this might be related to https://github.com/sensu/sensu-community-plugins/issues/1037 but I do not think it's a duplicate. The libfe error is fixed easily with installing libpq-dev. The following errors do not get fixed with that, I've at this point installed every debian package remotely related to postgresql.  I can install pg just fine with the system ruby/gem, but the embedded one inside of Sensu has problems.  

My system is an up to date Ubuntu LTS 14.04 server. 

This appears to be something related to openssl conflicts, see this issue in the Chef github repo.
https://tickets.opscode.com/browse/COOK-1406

Here is a gist of the long output of mkmf.log
https://gist.github.com/mhalligan/68eb61ad94696d3c629d

And here is the output of the gem installation command.

sudo /opt/sensu/embedded/bin/gem install pg -q --no-rdoc --no-ri
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    /opt/sensu/embedded/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/sensu/embedded/bin/ruby
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/
	--with-pqlib
	--without-pqlib
	--with-libpqlib
	--without-libpqlib
	--with-ms/libpqlib
	--without-ms/libpqlib

Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.18.1 for inspection.

Results logged to /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.18.1/ext/gem_make.out

**Comment by mvintila** [comment]
Also have this problem. If anyone has an workaround, so i can use the postgres related plugins, please share.

**Comment by maraca** [comment]
+1 - having this issue too

**Comment by phumpal** [comment]
+1 - same issue on 14.04.2

**Comment by mattyjones** [comment]
@phumpal @maraca @mvintila @mhalligan 

Please take a look here and see if the issue is resolved, it may not be.  If this is the case we can migrate this over.

https://github.com/sensu-plugins/sensu-plugins-postgres

Thanks

**Comment by vmihailenco** [comment]
@mattyjones  I don't understand what you mean. What should I try? How https://github.com/sensu-plugins/sensu-plugins-postgres can help with installing pg gem?

**Comment by cintiadr** [comment]
This issue was reopened in https://github.com/sensu-plugins/sensu-plugins-postgres/issues/1
