### ISSUE TITLE
Tiny typo leads to big confusion

### ISSUE THREAD

**Issue by gdhbashton** [sensu/sensu-community-plugins#1103]
In https://github.com/sensu/sensu-community-plugins/blob/master/handlers/other/ec2_node.rb#L72

the keyword `occurrences` is spelt `occurences` leading to a wonderfully-cryptic ` "error":"undefined method `>' for nil:NilClass"}` 

This is a single-byte fix - just add an `r` to spell `occurrences` correctly :)

Cheers,
Gavin.

**Comment by mattyjones** [comment]
@gdhbashton 

Thanks!
Fixed
