### ISSUE TITLE
Issue in wmi_metrics.rb with latest client 0.17.1-1

### ISSUE THREAD

**Issue by electricJP** [sensu/sensu-community-plugins#1113]
Hello,

I tried to upgrade 1 server to latest version. Sensu service starts but I receive an error in Uchiwa:

****

commandC:\opt\sensu\embedded\bin\ruby C:\etc\sensu\conf.d\extensions\wmi_metrics.rb
duration0.094
executed2015-04-02 13:21:26
handlerrelay
handlersrelay
history1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
interval30
issued2015-04-02 13:21:26
namewmi_metrics
outputC:/etc/sensu/conf.d/extensions/wmi_metrics.rb:26:in `<module:Extension>': uninitialized constant Sensu::Extension::Check (NameError)
 from C:/etc/sensu/conf.d/extensions/wmi_metrics.rb:25:in `<module:Sensu>'
 from C:/etc/sensu/conf.d/extensions/wmi_metrics.rb:24:in `<main>'
 
standalonetrue
status1
subscribersWindows-servers
total_state_change0
typemetric

****

error seems to be located here:
module Sensu 
  module Extension  
     class WMIMetrics < Check 
       def name 
        'wmi_metrics' 
      end 

Any idea?

**Comment by electricJP** [comment]
Hello,

Same problem with client 0.17.2.1:

outputC:/etc/sensu/conf.d/extensions/wmi_metrics.rb:26:in `<module:Extension>': uninitialized constant Sensu::Extension::Check (NameError)
 from C:/etc/sensu/conf.d/extensions/wmi_metrics.rb:25:in `<module:Sensu>'
 from C:/etc/sensu/conf.d/extensions/wmi_metrics.rb:24:in `<main>'

**Comment by electricJP** [comment]
Problem has been solved in the latest release 0.18.0.beta-1.

**Comment by electricJP** [comment]
I wrote to fast, it seems the service was running a previous version. I confirm I get the same error message with 0.18.0.beta-1.

**Comment by portertech** [comment]
@electricJP `wmi_metrics` is a Sensu check extension, not a check plugin. Check extensions are loaded from the extension directory and are not configured in the same fashion.

**Comment by electricJP** [comment]
Oh, so I posted in the wrong section, right?

**Comment by portertech** [comment]
@electricJP you're attempting to execute a check extension as you would a plugin, this is not correct. You may need to check your Windows service configuration XML to see where your client is loading extensions from, or add a path yourself, eg. `-e C:\opt\sensu\extensions`. Once you know where the extension directory is located, you can place `wmi_metrics.rb` in that director and restart your client.

**Comment by electricJP** [comment]
I think my setup is OK:

<service>
  <id>sensu-client</id>
  <name>Sensu Client</name>
  <description>This service runs a Sensu client</description>
  <executable>C:\opt\sensu\embedded\bin\ruby</executable>
  <arguments>C:\opt\sensu\embedded\bin\sensu-client -L WARN -d c:\etc\sensu\conf.d -e c:\etc\sensu\conf.d\extensions -l C:\opt\sensu\sensu-client.log</arguments>
</service>

 Directory of c:\etc\sensu\conf.d\extensions

02/24/2015  04:08 PM    <DIR>          .
02/24/2015  04:08 PM    <DIR>          ..
02/26/2015  12:59 PM             6,215 wmi_metrics.rb
               1 File(s)          6,215 bytes
               2 Dir(s)  83,100,098,560 bytes free

**Comment by portertech** [comment]
I do not recommend putting the `extensions` directory within the `conf.d` directory. Perhaps you should move it to ` c:\etc\sensu\extensions`, and then place `wmi_metrics.rb` within it, and then remove any check definitions that you've created for it.
