### ISSUE TITLE
check-ram plugin is broken on CentOS 7.1

### ISSUE THREAD

**Issue by psviderski** [sensu/sensu-community-plugins#1115]
When updating a CentOS machine to a new release 7.1 a new version (`3.3.10`) of the `procps-ng` package is installed. It introduces a new output format for the `free` utility: https://gitorious.org/procps/procps/commit/f47001c9e91a1e9b12db4497051a212cf49a87b1.
Prior to `3.3.10` the output of `free` command looks like this:
```
             total       used       free     shared    buffers     cached
Mem:        501560     466248      35312         80        856     218580
-/+ buffers/cache:     246812     254748
Swap:      2129916     112884    2017032
```
starting from `3.3.10` the output is changed to:
```
              total        used        free      shared  buff/cache   available
Mem:        1017640      100596      280784         216      636260      717600
Swap:       1023996         324     1023672
```
which breaks the `system/check-ram.rb` plugin.

This probably affects any other distributions which use `procps-ng>=3.3.10`.

**Comment by mattyjones** [comment]
@psviderski 

Thanks for bringing this up.  One of the big changes with the new repos is the removal of commands to do monitoring and replacing them with pure ruby.  The disk checks and raid checks are top on the list but I will make a not to try and figure this one out as well.

In the meantime I would be happy to field suggestions or accept pr's to fix this issue.

**Comment by mattyjones** [comment]
Please look here for any updates as the use of  free is officially being removed from sensu-plugins

https://github.com/sensu-plugins/sensu-plugins-memory-checks
