### ISSUE TITLE
MySQL Plugin check not working

### ISSUE THREAD

**Issue by kartrocket** [sensu/sensu-community-plugins#1136]
I have created a mysql check using the following config:

{
  "checks": {
    "cron_check": {
      "handlers": ["default"],
      "command": "/etc/sensu/plugins/mysql-connections.rb -h xxx.xxx.xxx.xxx -u sensu -p xxxx ",
      "interval": 60,
      "subscribers": [ "metamaster" ]
    }
  }
}

When I try to run the same on command line directly, it executes normally. Can someone please tell me why?

**Comment by mattyjones** [comment]
@kartrocket  What do you mean by "not working"  Could you provide any specific details, logs, etc.  Please take a look at the new repo as this check may have updated.

https://github.com/sensu-plugins/sensu-plugins-mysql

Thanks
