### ISSUE TITLE
check-ram issue

### ISSUE THREAD

**Issue by jennyfountain** [sensu/sensu-community-plugins#1158]
This change https://github.com/sensu/sensu-community-plugins/pull/1139 caused issues with the check on CentOS 6.6 systems.

/usr/bin/ruby /etc/sensu/community/plugins/system/check-ram.rb -w 7 -c 3
free: invalid option -- '-'
usage: free [-b|-k|-m|-g] [-l] [-o] [-t] [-s delay] [-c count] [-V]
  -b,-k,-m,-g show output in bytes, KB, MB, or GB
  -l show detailed low and high memory statistics
  -o use old format (no -/+buffers/cache line)
  -t display total for RAM + swap
  -s update every [delay] seconds
  -c update [count] times
  -V display version information and exit
CheckRAM WARNING: 5% free RAM left

Changing this 'free --help' to this 'free help' seems to work on both centOS 6 and centOS 7.

**Comment by burgerbisquit** [comment]
This works for me:
if `free --help 2>&1` =~ /.*wide output.*/

**Comment by mattyjones** [comment]
@jennyfountain @burgerbisquit 

Thanks for letting me know.  One of the major changes for the new plugins will be using pure ruby methods to get information like this so we avoid all issues with arch or distro specific crap.

**Comment by jmreicha** [comment]
I am experiencing a similar issue.  When running this script by hand, it doesn't seem to matter what options I pass to it, it always returns similar to the following output:

```
/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-ram.rb
free: invalid option -- '-'
usage: free [-b|-k|-m|-g] [-l] [-o] [-t] [-s delay] [-c count] [-V]
  -b,-k,-m,-g show output in bytes, KB, MB, or GB
  -l show detailed low and high memory statistics
  -o use old format (no -/+buffers/cache line)
  -t display total for RAM + swap
  -s update every [delay] seconds
  -c update [count] times
  -V display version information and exit
CheckRAM OK: 36% free RAM left
```

This is only happening on one of my systems so it is making me wonder if there is some dependency I am missing?  This is on Ubuntu 12.04.5.

**Comment by mattyjones** [comment]
Closing this issue as the use of free is being removed in the new repo

https://github.com/sensu-plugins/sensu-plugins-memory-checks
