### ISSUE TITLE
REMEDIATION: Recieved API Response (404)

### ISSUE THREAD

**Issue by gaga-github** [sensu/sensu-community-plugins#1162]
What would cause a 404 when trying to run 'touch /tmp/hello' on CentOS6.5?  The server has a subscription to its hostname, I don't see anything on the sensu-agent.log on the server showing it got the request and failed on something like permission denied.

Check's config:
<pre>
{
    "checks": {
        "check_jenkins_locall_http": {
            "interval": 30,
            "handlers": [
                "slack2-p1",
                "remediator"
            ],
            "standalone": false,
            "subscribers": [
              "centosJenkinsMaster"
            ],
            "command": "/usr/lib64/nagios/plugins/check_http localhost -t 30 -p 8080 -R \"Jenkins\"",
            "remediation": {
                "heavy_remediation": {
                    "occurrences": [
                        "1+"
                    ],
                    "severities": [
                        2
                    ]
                }
            }
        },
        "heavy_remediation": {
            "command": "/bin/touch /tmp/hello",
            "subscribers": [],
            "handlers": [
                "slack2-p1"
            ],
            "publish": false
        }
    }
}
</pre>

server's sensu config:
<pre>
{
  "client": {
    "safe_mode": false,
    "subscriptions": [
      "sensu-default",
      "centosJenkinsMaster",
      "jenkinsrelease.example.net"
    ],
    "address": "10.10.10.10",
    "bind": "127.0.0.1",
    "name": "jenkinsrelease.example.net"
  }
}
</pre>

**Comment by sprGeoffrey** [comment]
I'm having this same issue.  Here's my config:
```
{
  "checks": {
    "test_please_ignore": {
      "handlers": ["default", "remediator"],
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-cmd.rb -c false",
      "interval": 60,
      "subscribers": [ "build" ],
      "publish": true,
      "remediation": {
        "test_please_ignore_rem": {
          "occurrences": ["1+"],
          "severities": [2]
        }
      }
    },
    "test_please_ignore_rem": {
        "handlers": ["default"],
        "command": "echo remediation >> /tmp/remediation",
        "subscribers": [],
        "publish": false
    }
  }
}
```

Am not seeing `/tmp/remediation` on the "build" host or the sensu server.  Also I'm not seeing any indication that there was an error or the remediation tried to run.  What am I doing wrong?

**Comment by jperville** [comment]
Hello there, having the same issue when the sensu server and client are on different machines (or VMs). The remediation works only when server and client are on the same machine (or VM).

If the (unpublished) remediation check is only present on the client, the `/var/log/sensu-server.log` on the server displays a line like:

```json
{"timestamp":"2015-06-06T10:32:38.764508+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/remediator.rb","name":"remediator"},"output":["REMEDIATION: Evaluating remediation: xxx-vm {\"apt-cacher-ng-restart\"=>{\"occurrences\"=>[\"1+\"], \"severities\"=>[2]}} #=5 sev=2\n","REMEDIATION: Triggering remediation check 'apt-cacher-ng-restart' for [\"xxx-vm\"]\n","REMEDIATION: Received API Response (404): , exiting.\n"]}
```

My workaround is to create the unpublished check on the server also (even if it will never run there), just so that the API does not return 404 when queried for the check:

```sh
{
  "checks": {
    "apt-cacher-ng-restart": {
      "command": "sudo /usr/sbin/service apt-cacher-ng restart",
      "handlers": [
        "default"
      ],
      "subscribers": [],
      "publish": false,
      "interval": 10
    }
  }
}
```

After doing this, the remediation check will return as expected on the client.

Note: using sensu 0.18.1 (installed and configured with the sensu-chef cookbook version 2.10.0).

**Comment by jperville** [comment]
After investigating more on how sensu checks work, I think that the unpublished remediation checks cannot be standalone (defined on the client). It does not help me, and in the end I may have to fallback to ad-hoc remediation handler, which is not DRY at all.

**Comment by MikeMester** [comment]
any update on this?  I am using sensu .20 and this still seems to be an issue with the remediator.  Basically just looking for a simple apache restart.  

This is the log entry on the server:

```
 "output":["REMEDIATION: Evaluating remediation: LAMP01 {\"light_remediation\"=>{\"occurrences\"=>    [1, 2], \"severities\"=>[2]}} #=1 sev=2\n","REMEDIATION: Triggering remediation check 'light_remediation' for [\"LAMP01\"]\n","REMEDIATION: Received API Response (404): , exiting.\n"]
```
Light Remediation Check

```
root@sensu:/etc/sensu/conf.d# cat light_remediation.json
{

 "checks":{

   "light_remediation": {
       "command": "/usr/sbin/service restart apache2",
       "subscribers": [],
       "handlers": ["debug"],
       "publish": false
       },


    }
}

```

Finally the actual check

```
{
   "checks":{
     "apache-status-central":{
        "command":"/etc/sensu/plugins/check-http.rb -u http://lamp01/",
        "interval":30,
        "subscribers":["apache"],
        "handlers":["default","remediator"],

        "remediation": {
         "light_remediation": {
           "occurrences": [1, 2],
           "severities": [2]
          }
        }
      }
  }
}

```
Client Config on Lamp01

```
{
   "client": {
    "name": "LAMP01",
    "address": "10.0.5.17",
    "subscriptions":["linux","apache","LAMP01"]
  }
}

```

Thanks!

**Comment by jperville** [comment]
@MikeMester your remediation check definition has a typo (comma at end of line) this could explain why the check returns 404 when the server triggers it (if it is invalid javascript it is probably skipped, maybe with a warning in the log).

You should also update the remediation command to "sudo /usr/sbin/service apache2 restart" and add a sudoers entry as below.

```sh
root@xxx:~# cat /etc/sudoers.d/sensu-apache
sensu ALL=(root:sensu) NOPASSWD:/usr/sbin/service apache2 restart
```

Other than that, your check definitions look fine to me.

**Comment by MikeMester** [comment]
awesome!  that is working and i did the sudoers as well.  Thank you

**Comment by shakycode** [comment]
I'm having a similar issue as @MikeMester @jperville Can you take a look at my configuration?

On the sensu server I have the light remediation check

`light_remediation.json`

````
{

 "checks":{

   "light_remediation": {
       "command": "/bin/sh /etc/sensu/plugins/puma_restart.sh",
       "subscribers": [],
       "handlers": ["debug"],
       "publish": false
       }


    }
}
````
And now the actual check

`check_memory_puma.json ` Note: The check mem warning/critical values are blown up high just to trigger the check and test.  These will be scaled back down once I get this working.

````
{
   "checks":{
     "memory_puma":{
        "command":"/etc/sensu/plugins/check-mem.sh -w 90000000 -c 100000000",
        "interval":10,
        "subscribers":["rh"],
        "handlers":["default","remediator", "mailer"],

        "remediation": {
         "light_remediation": {
           "occurrences": [1, 2],
           "severities": [2]
          }
        }
      }
  }
}   
````
Here is the endpoint/client configuration
`client.json`

````
{
  "client": {
    "name": "university",
    "address": "25.93.64.141",
    "subscriptions": [
      "linux", "web-server", "rh"
    ]
  }
}
````

After adding this to sensu, flushing redis, restarting sensu server/api/etc In my sensu-server.log I get the following output.

````
{"timestamp":"2016-04-19T19:26:47.535032-0500","level":"info","message":"processing event","event":{"id":"cce4da9f-31ff-4e73-8f1d-afcd02cacb79","client":{"name":"university","address":"25.93.64.141","subscriptions":["linux","web-server","rh"],"version":"0.20.3","timestamp":1461112003},"check":{"command":"/etc/sensu/plugins/check-mem.sh -w 90000000 -c 100000000","interval":10,"subscribers":["rh"],"handlers":["remediator","mailer"],"remediation":{"light_remediation":{"occurrences":[1,2],"severities":[1]},"medium_remediation":{"occurrences":["3-10"],"severities":[1]},"heavy_remediation":{"occurrences":["1+"],"severities":[2]}},"name":"memory_puma","issued":1461112007,"occurrences":1,"refresh":10,"executed":1461112007,"duration":0.012,"output":"MEM CRITICAL - free system memory: 5665 MB\n","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":43,"action":"create"}}
````

````
{"timestamp":"2016-04-19T19:26:48.108427-0500","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/remediator.rb","name":"remediator"},"output":["REMEDIATION: Evaluating remediation: university {\"light_remediation\"=>{\"occurrences\"=>[1, 2], \"severities\"=>[1]}, \"medium_remediation\"=>{\"occurrences\"=>[\"3-10\"], \"severities\"=>[1]}, \"heavy_remediation\"=>{\"occurrences\"=>[\"1+\"], \"severities\"=>[2]}} #=43 sev=2\n","REMEDIATION: Matchdata: #<MatchData \"1+\" 1:\"1\">\n","REMEDIATION: Triggering remediation check 'heavy_remediation' for [\"university\"]\n","REMEDIATION: Recieved API Response (404): , exiting.\n"]}
````

And just a sample of the client log on the endpoint

````
{"timestamp":"2016-04-19T19:29:07.539531-0500","level":"info","message":"publishing check result","payload":{"client":"university","check":{"name":"memory_puma","issued":1461112147,"command":"/etc/sensu/plugins/check-mem.sh -w 90000000 -c 100000000","executed":1461112147,"duration":0.011,"output":"MEM CRITICAL - free system memory: 5665 MB\n","status":2}}}
````

I'm really confused as to why this is happening.  I'm a bit new to using remediation and really need a hand getting this working.  My purpose is to check for a certain memory threshold then execute a script on the endpoint that restarts puma (rails/ruby app server).  The script works fine, but I'm getting the API 404 error as others have experienced.

Any help?  I'm about to dropkick my computer 👍

**Comment by jperville** [comment]
Hi @shakycode ,

Your problem is here: `"output":["REMEDIATION: Evaluating remediation: >>>university<<< {\"light_remediation\" [snip]`, 

Here is how it works: when the sensu check fails, the remediator handler is invoked; then the remediator handler emits a custom check request ("light_remediation") which is targeted at the affected client only; the "hack" to make the check request go only to the affected client is to make each client subscribe it their own name (which must be unique and cannot be an existing subscription name such as "db" or "web-server").

Try modifying the client.json like this:
```json
{
  "client": {
    "name": "university",
    "address": "25.93.64.141",
    "subscriptions": [
      "linux", "web-server", "rh", "university"
    ]
  }
}
```

Then restart the sensu client and report us your success.

**Comment by shakycode** [comment]
@jperville Ok I did exactly what you said.  Restarted the client also flushed redis/restarted sensu on the server to have a clean point.

Here's what my client.json looks like on the university box:
````
{
  "client": {
    "name": "university",
    "address": "25.93.64.141",
    "subscriptions": [
      "linux", "web-server", "puma", "university"
    ]
  }
}
````

I'm still getting the same error after restart everything and flushing redis

````
{"timestamp":"2016-04-20T05:02:27.542075-0500","level":"info","message":"processing event","event":{"id":"ec7133d6-901d-4bd2-b16b-015fc4f52394","client":{"name":"rh","address":"25.134.7.96","subscriptions":["linux","web-server","puma","rh"],"version":"0.20.3","timestamp":1461146545},"check":{"command":"/etc/sensu/plugins/check-mem.sh -w 900000 -c 1000000","interval":10,"subscribers":["puma"],"handlers":["default","remediator","mailer"],"remediation":{"light_remediation":{"occurrences":[1,2],"severities":[2]}},"name":"memory_puma","issued":1461146547,"executed":1461146547,"duration":0.014,"output":"MEM CRITICAL - free system memory: 13601 MB\n","status":2,"history":["2","2"],"total_state_change":0},"occurrences":2,"action":"create"}}
{"timestamp":"2016-04-20T05:02:27.557410-0500","level":"info","message":"handler output","handler":{"type":"pipe","command":"cat","name":"default"},"output":["{\"id\":\"ec7133d6-901d-4bd2-b16b-015fc4f52394\",\"client\":{\"name\":\"rh\",\"address\":\"25.134.7.96\",\"subscriptions\":[\"linux\",\"web-server\",\"puma\",\"rh\"],\"version\":\"0.20.3\",\"timestamp\":1461146545},\"check\":{\"command\":\"/etc/sensu/plugins/check-mem.sh -w 900000 -c 1000000\",\"interval\":10,\"subscribers\":[\"puma\"],\"handlers\":[\"default\",\"remediator\",\"mailer\"],\"remediation\":{\"light_remediation\":{\"occurrences\":[1,2],\"severities\":[2]}},\"name\":\"memory_puma\",\"issued\":1461146547,\"executed\":1461146547,\"duration\":0.014,\"output\":\"MEM CRITICAL - free system memory: 13601 MB\\n\",\"status\":2,\"history\":[\"2\",\"2\"],\"total_state_change\":0},\"occurrences\":2,\"action\":\"create\"}"]}
{"timestamp":"2016-04-20T05:02:28.072295-0500","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/remediator.rb","name":"remediator"},"output":["REMEDIATION: Evaluating remediation: university {\"light_remediation\"=>{\"occurrences\"=>[1, 2], \"severities\"=>[2]}} #=2 sev=2\n","REMEDIATION: Triggering remediation check 'light_remediation' for [\"university\"]\n","REMEDIATION: Recieved API Response (404): , exiting.\n"]}
````
Any other thoughts?  I swapped out the `rh` subscription on all endpoints since one of the endpoints hostname was `rh` for a general subscription of `puma`  But I've isolated the university machine for testing and added `university` to the client.json on university and no luck.  Any other thoughts?  

Should I try to put these checks on the actual client too? Or just leave them on the sensu server (master)?

**Comment by jperville** [comment]
Hi @shakycode,

The check definitions and the remediator plugin go on the sensu server (remediation is incompatible with standalone checks). The client definition ("client.json") go on the sensu client ("university").

Make sure you have restarted the sensu client ("university"); if you are using a graphical frontend such as "uchiwa" can you show me the list of subscriptions for client "university" as seen by the server?

Also, be careful of typos, I once made a typo in "occurrences" and I spent some time figuring out why my remediation was not triggering (in your case it is triggering, but 404, so I think that the server is not aware of the light_remediation check).

Here is a real world, working example, that I have on my server:

```sh
root@staging4-backends-lb:/etc/sensu/conf.d/checks# cat fstab-mounts.json 
{
  "checks": {
    "fstab-mounts": {
      "command": "check-fstab-mounts.rb",
      "handlers": ["default", "remediator"],
      "subscribers": ["system"],
      "interval": 60,
      "occurrences": 1,
      "refresh": 600,
      "remediation": {
        "fstab-mounts-remediation": {
          "occurrences": ["1+"],
          "severities": [2]
        }
      }
    }
  }
}
root@staging4-backends-lb:/etc/sensu/conf.d/checks# cat fstab-mounts-remediation.json 
{
  "checks": {
    "fstab-mounts-remediation": {
      "command": "sudo /bin/mount -a && sudo /sbin/swapon -a",
      "handlers": ["default"],
      "subscribers": [],
      "publish": false,
      "interval": 30
    }
  }
}
root@staging4-backends-lb:/etc/sensu/conf.d/checks# cat ../client.json 
{
  "client": {
    "name": "staging4-backends-lb",
    "address": "192.168.0.1",
    "subscriptions": [
...
      "staging4-backends-lb",
      "system"
    ],
    "node": "staging4:staging4-backends-lb"
  }
}
```

To test the check, I type 'swapoff -a' and the remediation should trigger, mounting the swap.

Note that since running 'swapon -a' and mounting are privileged action I had to allow the `sensu` users to run these actions passwordless during the remediation, see below.

```sh
root@staging4-backends-lb:/etc/sensu/conf.d/checks# cat /etc/sudoers.d/sensu-mount 
sensu ALL=(root:sensu) NOPASSWD:/bin/mount -a
sensu ALL=(root:sensu) NOPASSWD:/sbin/swapon -a
```

Can you try to run my example on your server?

**Comment by shakycode** [comment]
@jperville Hi there, thanks for the early response.  Here's my setup now:

**/etc/sensu/conf.d/checks/check_memory_puma.json**
````
{
  "checks": {
    "memory_puma": {
      "command": "/etc/sensu/plugins/check-mem.sh -w 900000 -c 1000000",
      "handlers": ["default", "remediator", "mailer"],
      "subscribers": ["system"],
      "interval": 10,
      "occurrences": 1,
      "refresh": 10,
      "remediation": {
        "light_remediation": {
          "occurrences": ["1+"],
          "severities": [2]
        }
      }
    }
  }
}   
````
**/etc/sensu/conf.d/checks/light_remediation.json **
````
{
  "checks": {
    "light_remediation": {
      "command": "/etc/sensu/plugins/puma_restart.sh",
      "handlers": ["default"],
      "subscribers": [],
      "publish": false,
      "interval": 30
    }
  }
}
````
** end point /etc/sensu/conf.d/client.json **
````
{
  "client": {
    "name": "university",
    "address": "25.93.64.141",
    "subscriptions": [
      "linux", "web-server", "system", "university"
    ]
  }
}
````
In uchiwa here is the list of the subscriptions for University
![Image of Yaktocat](http://s31.postimg.org/7cgerujx7/Screen_Shot_2016_04_20_at_5_46_35_AM.png)

Even after setting it up nearly identical (I cut/pasted your configuration and just used my script), this is what I get in the sensu-server.log

````
{"timestamp":"2016-04-20T05:49:08.139697-0500","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/remediator.rb","name":"remediator"},"output":["REMEDIATION: Evaluating remediation: university {\"light_remediation\"=>{\"occurrences\"=>[\"1+\"], \"severities\"=>[2]}} #=63 sev=2\n","REMEDIATION: Matchdata: #<MatchData \"1+\" 1:\"1\">\n","REMEDIATION: Triggering remediation check 'light_remediation' for [\"university\"]\n","REMEDIATION: Recieved API Response (404): , exiting.\n"]}
````

I'm ready to give up and restart this stuff manually when alerts come... but that's going against the remediation technique that I'm trying to achieve :(

**Comment by jperville** [comment]
Can you show a screenshot of the "checks" tab in uchiwa where the light_remediation should be listed?

**Comment by shakycode** [comment]
@jperville Here's the screenshot for checks in uchiwa

![uchiwa](http://s31.postimg.org/3xbb2ji3f/Screen_Shot_2016_04_20_at_5_56_41_AM.png)

**Comment by jperville** [comment]
Have to go lunch, but the next step we will investigate is if your remediation request made it to the sensu API (which is not same process as the sensu server).

**Comment by shakycode** [comment]
@jperville ok thanks.  Hope to hear from you soon.  You can also reach me directly at: jelinek@gmail.com or on twitter as "shakycode" 👍

**Comment by shakycode** [comment]
@jperville FYI here's an excerpt of my API log from the sensu server:

````
{"timestamp":"2016-04-20T06:19:59.080800-0500","level":"info","message":"POST /checks/request","remote_address":"127.0.0.1","user_agent":"Ruby","request_method":"POST","request_uri":"/checks/request","request_body":"{\"check\":\"light_remediation\",\"subscribers\":[\"university\"]}"}
````

And here's a log excerpt from the university endpoint from the sensu-client.log
````
{"timestamp":"2016-04-20T06:21:39.250195-0500","level":"warn","message":"previous check command execution in progress","check":{"name":"memory_puma","issued":1461151299,"command":"/etc/sensu/plugins/check-mem.sh -w 900000 -c 1000000"}}
{"timestamp":"2016-04-20T06:21:39.260468-0500","level":"info","message":"publishing check result","payload":{"client":"university","check":{"name":"memory_puma","issued":1461151299,"command":"/etc/sensu/plugins/check-mem.sh -w 900000 -c 1000000","executed":1461151299,"duration":0.013,"output":"MEM CRITICAL - free system memory: 5517 MB\n","status":2}}}
````
Hope this helps some :)

**Comment by jperville** [comment]
In my logs, the remediator posts to `/request` and not to `/checks/request`.

Can you edit `/etc/sensu/handlers/remediator.rb` on your sensu server and modify the `trigger_remediation` method at the end to look like this?

```
  # Issue a check via the API
  def trigger_remediation(check, subscribers)
    api_request(:POST, '/request') do |req|
      req.body = JSON.dump('check' => check, 'subscribers' => subscribers)
    end
  end
```

The problem is probably because a route has moved since earlier version, and then the 404 response from API to the remediator is totally justified.

Note: I am using sensu 0.20.6-1, but I started using the remediator plugin around version 0.18.

**Comment by shakycode** [comment]
@jperville OMG YES! editing the remediator.rb and changing the API post path worked like a champ.  I'm all good now!

**Comment by jperville** [comment]
For information, the code of my remediator plugin is this version (the last one before "good bye" commit) : https://github.com/sensu/sensu-community-plugins/blob/e58c1f3ce39c6c0ca271fadd470c04362e92b190/handlers/remediation/sensu.rb

**Comment by jperville** [comment]
It looks like we have solved this issue, some users were using broken implementation of the remediator plugin which posted to `/checks/request` instead of `/request`, resulting in a deserved 404 response from API.

**Comment by shakycode** [comment]
@jperville thanks so much, I'm remediating!!! Shirt and gift coming your way 👍
