### ISSUE TITLE
Please use Socket.gethostbyname in all plugins

### ISSUE THREAD

**Issue by jcmartins** [sensu/sensu-community-plugins#1176]
Hi, I'm have problems with amazon instance_id,  please change Socket.gethostname to Socket.gethostbyname.

irb(main):002:0> Socket.gethostname
=> "master.jenkins.dev.us-east-1"
irb(main):003:0> Socket.gethostbyname(Socket.gethostname).first
=> "i-59f8d7a4.master.jenkins.dev.us-east-1.titansgroup.net"

tks
João

**Comment by mattyjones** [comment]
Closing this here as it is already opened in the new repo
