### ISSUE TITLE
Slack Integration issues

### ISSUE THREAD

**Issue by dayhkr** [sensu/sensu-community-plugins#1179]
Having a hard time getting the slack.rb handler to fire properly.  I have defined a new handler with the following settings.

{
  "handlers":{
    "slack":{
      "type":"pipe",
      "command":"/etc/sensu/handlers/slack.rb -j /etc/sensu/handlers/slack.json"
    }
  }
}

I defined the slack settings in slack.json (web hook, channel and bot name), but when the handler gets called I get the following errors.

"output":["/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1533:in `addr_port': undefined method `+' for nil:NilClass (NoMethodError)\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1466:in `begin_transport'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1408:in `transport_request'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1373:in `request'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:85:in `api_request'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:120:in `stash_exists?'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:132:in `block (2 levels) in filter_silenced'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:97:in `timeout'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:131:in `block in filter_silenced'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:129:in `each'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:129:in `filter_silenced'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:31:in `filter'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'\n"]

**Comment by bsnape** [comment]
I _think_ your handler might be constructed incorrectly.

I haven't hand-built mine (Puppet takes care of that) but it looks like this:

```json
{
  "slack": {
    "webhook_url": "https://hooks.slack.com/services/<redacted>",
    "bot_name": "sensu",
    "channel": "#redacted"
  },
  "handlers": {
    "slack": {
      "command": "/srv/sensu-community-plugins/embedded/service/sensu-community-plugins/handlers/notification/slack.rb",
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "type": "pipe"
    }
  }
}
```

However, I don't specify the `-j` flag like you have so I'm not sure how that might affect things.

Hopefully this will give you some pointers though.

**Comment by dayhkr** [comment]
This doesn't work with or without the -j flag and that is not needed unless you define your config with a different name.  I still can't get this to work no matter how I format the config files and I haven't been able to figure out why at this point..

**Comment by TrentScholl** [comment]
Hi dayhkr,

If you're still having this issue - make sure the api section of your config.json includes a host

eg.
```
  "api": {
    "host": "localhost",
    "port": 4567
  }
```

**Comment by stack72** [comment]
@TrentScholl thanks so much for posting this - this fixed the exact same issue for me

:beers:

**Comment by dayhkr** [comment]
Yeah that is exactly what I forgot I found it a day later and fix it.  Glad you posted this up here for others because it took a lot of digging to find that.

**Comment by soichih** [comment]
@TrentScholl thanks so much for posting this - this fixed the exact same issue for me

**Comment by soichih** [comment]
@TrentScholl thanks so much for posting this - this fixed the exact same issue for me

**Comment by talaris** [comment]
So I think part of the issue also is that the -j parameter is looking a key to use not a path to a json file. The JSON files should be in the configuration directories of Sensu, by default `/etc/sensu/conf.d/`.

We actually use the -j to setup different handlers to report to different channels.

```
{
  "slack": {
    "webhook_url": "https://hooks.slack.com/services/<redacted>",
    "bot_name": "sensu",
    "channel": "#primary"
  },
  "slack-ops": {
    "webhook_url": "https://hooks.slack.com/services/<redacted>",
    "bot_name": "sensu",
    "channel": "#ops"
  },
  "handlers": {
    "slack": {
      "command": "/srv/sensu-community-plugins/embedded/service/sensu-community-plugins/handlers/notification/slack.rb",
      "type": "pipe"
    },
    "slack-ops": {
      "command": "/srv/sensu-community-plugins/embedded/service/sensu-community-plugins/handlers/notification/slack.rb -f slack-ops",
      "type": "pipe"
    }
  }
}
```
