### ISSUE TITLE
check_mem doesn't work on CentOS7

### ISSUE THREAD

**Issue by soichih** [sensu/sensu-community-plugins#1188]
The command executed by check_mem plugin doesn't work on CentOS 7.1

```
# free -m | grep buffers/cache
#
```

free -m is outputting in "redhat" format, so it should just be able to treat CentOS 7.1 as redhat and plugin should work(?)

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7823        1776         554         142        5492        5618
Swap:          2047          10        2037
```

I've updated following 

```
if [ -f /etc/redhat-release ] && [ `awk '{print $3}' /etc/redhat-release` = "21" ]; then
  FREE_MEMORY=`free -m | grep Mem | awk '{ print $7 }'`
else
  FREE_MEMORY=`free -m | grep buffers/cache | awk '{ print $4 }'`
fi
```

to just ..

```
if [ -f /etc/redhat-release ]; then
  FREE_MEMORY=`free -m | grep Mem | awk '{ print $7 }'`
else
  FREE_MEMORY=`free -m | grep buffers/cache | awk '{ print $4 }'`
fi
```

And check_mem seems to be working on CentOS 7.

**Comment by christianTragesser** [comment]
Same for the mem percentage script as well.  This would be needed for procps-ng 3.3.9-6 or later in CentOS:

$rpm -q --changelog procps-ng
.....
* Thu Feb 27 2014 Jaromir Capik <jcapik@redhat.com> - 3.3.9-6
- Subtracting Shmem from Cached (#1070736)

**Comment by mattyjones** [comment]
This check is going away shortly in the new [sensu-plugins-memory-checks](https://github.com/sensu-plugins/sensu-plugins-memory-checks) gem.  Going forward shortly pure Ruby that is platform and arch independent will be the favored and supported solution.  We are not there yet and checks in other languages will ALWAYS be welcome but will be unsupported officially.

**Comment by mattyjones** [comment]
@soichih Please take a look at the new repo posted above for any updates.

Thanks!
