### ISSUE TITLE
Slack alert getting cut off

### ISSUE THREAD

**Issue by jmreicha** [sensu/sensu-community-plugins#1192]
I am attempting to get some custom info in my slack alerts but it seems that adding the `message_prefix` is causing weirdness in the slack message formatting.

For example, I would like the entire message with extra message prefix stuff to be posted but the last line is getting cut off and the "Show more..." appears on the same line as the last part of the message.

![image](https://cloud.githubusercontent.com/assets/1039098/7895019/77641dfe-063e-11e5-9d45-41bcec5df220.png)

Here is an example of what I would like the message to look like by default.

![image](https://cloud.githubusercontent.com/assets/1039098/7895109/bceec268-0641-11e5-820a-c0a44fdb8d53.png)

The message formats correctly if I don't include message_prefix but obviously it would be nicer to include the additional information.

Does anybody know what I can do to fix this?

**Comment by mattyjones** [comment]
@jmreicha Can you please use the updated plugins and if the issue still persists then open an issue there and we will be glad to help.

https://github.com/sensu-plugins/sensu-plugins-slack

Thanks!
