### ISSUE TITLE
check_log configuration error

### ISSUE THREAD

**Issue by romariolodder** [sensu/sensu-community-plugins#1209]
I'm using the check_log to check my logfiles on certain keywords, for example "error". If a new error is written to the log file, sensu gives me an error. After a couple of seconds, the critical error disappears. How should I configure my check in order to check the log file on a word like ERROR and that the error stays as long the error exists in the log file?

My check looks a bit like this:

 {
  "checks": {
    "check_log": {
      "command": "/etc/sensu/plugins/check-log.rb -f /opt/test/logs/testDocker.log -q 'ERROR'",
      "interval": 10,
      "subscribers": ["subscriber1"]
    }
  }
}

**Comment by mattyjones** [comment]
https://github.com/sensu-plugins/sensu-plugins-logs/issues/1
