### ISSUE TITLE
Wrong format for InfluxDB 0.9.1?

### ISSUE THREAD

**Issue by alpern95** [sensu/sensu-community-plugins#1216]
Hello, 
I use influxdb 0.9.2 and
i have now the new gem influxdb version 0.1.9 , 
i use sensu with the handler influxdb with the command influxdb-metrics.rb.
I have now a reject from the influxdb api.
the new api do not accept write without TAG.
I dont know how to add a tag on the output for my metrics. 
perhaps i need to modify myself influxdb-metrics.rb?
Log sensu
(influxdb_1 | [http] 2015/07/22 17:28:36 172.17.1.89 - - [22/Jul/2015:17:28:36 +0000] POST /write?db=sensu&precision=s&u=sensu&p=pass HTTP/1.1 400 77 - Ruby 15c25a18-3097-11e5-853a-000000000000 3.144229ms)
( influxdb_1 | [http] 2015/07/22 17:27:10 10.0.163.173 - sensu [22/Jul/2015:17:27:10 +0000] POST /write?consistency=&db=sensu&precision=&rp= HTTP/1.1 204 0 - InfluxDBClient e2313ba8-3096-11e5-8514-000000000000 10.766309ms )
End Log

I have also a client telegraf for influxdb, this client who use the same base and works perfectly.

If you have an advice/idee for me Thank.

**Comment by JulienChampseix** [comment]
will be usefull +1

**Comment by yongtin** [comment]
I made a pull request here. https://github.com/sensu/sensu-community-plugins/pull/1225

**Comment by Brawnd0** [comment]
#1225 Worked for me.  Thanks @yongtin
