### ISSUE TITLE
check-fstab-mounts.rb gets confused about swap and UUIDs

### ISSUE THREAD

**Issue by petere** [sensu/sensu-community-plugins#1244]
I have this line in `/etc/fstab`:

    UUID=f63ec6bf-adb7-4684-8528-7c126cebf167 swap                    swap    defaults        0 0

This causes the check script to fail:

```
# ./check-fstab-mounts.rb
Check failed to run: No such file or directory - /etc/sensu/community/plugins/system/UUID=f63ec6bf-adb7-4684-8528-7c126cebf167, ["./check-fstab-mounts.rb:61:in `realpath'", "./check-fstab-mounts.rb:61:in `realpath'", "./check-fstab-mounts.rb:61:in `block (2 levels) in check_mounts'", "./check-fstab-mounts.rb:61:in `select'", "./check-fstab-mounts.rb:61:in `block in check_mounts'", "./check-fstab-mounts.rb:52:in `each'", "./check-fstab-mounts.rb:52:in `check_mounts'", "./check-fstab-mounts.rb:67:in `run'", "/usr/lib64/ruby/gems/1.9.1/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

Apparently, it does not know about the UUID syntax at all.

It would be great if there was a way to exclude file system types (opposite of `-t`), to exclude swap but check all other file system types.

**Comment by analytically** [comment]
This repo is old. Can you try https://github.com/sensu-plugins/sensu-plugins-disk-checks?
