### ISSUE TITLE
CheckDisk WARNING: /sys/kernel/debug/tracing Unable to read.

### ISSUE THREAD

**Issue by Antikythera** [sensu/sensu-community-plugins#1251]
I'm getting this error on one server running Ubuntu 15.10. Funny thing is, it doesn't appear on the other server also running Ubuntu 15.10.
![screen shot 2015-12-24 at 9 26 05 pm](https://cloud.githubusercontent.com/assets/5049882/11997742/fab9984c-aa84-11e5-951c-ce2c26c74d8b.png)
I then thought maybe it's requires enabling tracing on system level.
```
echo 1 > /sys/kernel/debug/tracing/tracing_on
```
It didn't help.
Googling for this error didn't seem to show anything related. Not sure what to do anymore, I tried checking permissions and basic stuff like that, I'm new to sensu.

**Comment by Antikythera** [comment]
Well, the error is actually quite self explanatory.
`sensu` user must have read rights for `/sys/kernel/debug` directory.
Fix:
```bash
chown -R root:sensu /sys/kernel/debug
chmod -R g+r /sys/kernel/debug 
```

**Comment by marji** [comment]
I've been experiencing the same problem on a Ubuntu 15.10 server.
I cannot figure out what this permission error is caused by. 
Other servers (running 14.04) have /sys/kernel/debug as root:root 0700 and have no issues, so IMHO the problem must be caused by something different than ownership on /sys/kernel/debug.

**Comment by strictlyd** [comment]
@marji Could possibly related to this, [https://bugs.launchpad.net/ubuntu/+source/nagios-plugins/+bug/1516451](). There's some explanations about the differences between 14.04 and 15.05/15.10.

**Comment by Antikythera** [comment]
Still happening on the latest version (0.23). The workaround I posted above doesn't work anymore. To avoid confusion, it didn't stop working after I upgraded from 0.21. It stopped working for no apparent reason on the same version I reported the fix working for me.
