### ISSUE TITLE
mailer.rb and sensu-handler.rb errors

### ISSUE THREAD

**Issue by vvm7ua** [sensu/sensu-community-plugins#1254]
Get the next error with plugin https://github.com/sensu-plugins/sensu-plugins-mailer

# cat /etc/sensu/conf.d/mailer.json | /opt/sensu/embedded/bin/ruby /etc/sensu/handlers/handler-mailer.rb 
/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:128:in `+': no implicit conversion of nil into String (TypeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:128:in `filter_silenced'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:31:in `filter'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'

OS Ubuntu 14.04.3 LTS

Whats wrong?

Thanks!

**Comment by vvm7ua** [comment]
Fixed!
configuration issue.

**Comment by Koen76** [comment]
what did you configure wrong? because I have the same issue
