### ISSUE TITLE
check-procs.rb just broke

### ISSUE THREAD

**Issue by jmreicha** [sensu/sensu-community-plugins#1257]
On one of my hosts [this commit](https://github.com/sensu/sensu-community-plugins/commit/49c308d3a4bc519213ffb191dd82828df43d9554) just broke the check-procs.rb plugin for me.

I changed the following and it works, but I'm still trying to figure out why it broke on just one host...

```
option :warn_over,
         short: '-w N',
         long: '--warn-over N',
         description: 'Trigger a warning if over a number',
         proc: proc(&:to_i)
         #default: 1

  option :crit_over,
         short: '-c N',
         long: '--critical-over N',
         description: 'Trigger a critical if over a number',
         proc: proc(&:to_i)
         #default: 1
```

**Comment by analytically** [comment]
@mattyjones

**Comment by jmreicha** [comment]
I'm just going to close, the sensu-plugins version is working.
