### ISSUE TITLE
logstash handler sending invalid timestamp?

### ISSUE THREAD

**Issue by MattMencel** [sensu/sensu-community-plugins#453]
I am getting errors like this

    :exception=>java.lang.IllegalArgumentException: Invalid format: "2014-01-29T18:46:00Z" is malformed at "Z"

in my server.log on my logstash server.  More detail...

    {:timestamp=>"2014-01-29T12:46:00.656000-0600", :message=>"{\"@source\":\"sensu.my.dom\",\"@type\":\"sensu-logstash\",\"@tags\":[\"sensu-ALERT\"],\"@fields\":{\"short_message\":\"ALERT - sensu.my.dom/redis_process: Redis is not running\",\"full_message\":\"CheckProcs OK: Found 1 matching processes; cmd /redis-server/\\n\",\"host\":\"sensu.my.dom\",\"timestamp\":1391021147,\"address\":\"10.50.2.16\",\"check_name\":\"redis_process\",\"command\":\"/etc/sensu/plugins/check-procs.rb -p redis-server -C 1\",\"status\":0,\"flapping\":null,\"occurrences\":1,\"action\":null},\"@timestamp\":\"2014-01-29T18:46:00Z\"}", :exception=>java.lang.IllegalArgumentException: Invalid format: "2014-01-29T18:46:00Z" is malformed at "Z", :backtrace=>["org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:754)"

I can post more of the stacktrace if necessary or put it in a Gist.  I guess logstash doesn't like that "Z" is passed in the timestamp without a valid tz offset like "0600"?  I'm running logstash 1.3.3.

The JSON is built in the Sensu logstash handler, I've tested the bit of code that builds @timestamp in IRB....and that's exactly the format it's creating it in.

Should I post this as a bug to logstash?

**Comment by mattyjones** [comment]
@MattMencel Is this still an issue that you would like help with?  If not I would like to close this in a at the end of the month.

Thanks

**Comment by MattMencel** [comment]
Closing
