### ISSUE TITLE
system_profile extension file_chunk_size bug?

### ISSUE THREAD

**Issue by srenatus** [sensu/sensu-community-plugins#507]
Hi there.

With a monstrous `/proc/stat` file (above 4k), [the following function call in extensions/system_profile.rb](https://github.com/sensu/sensu-community-plugins/blob/master/extensions/checks/system_profile.rb#L92-L105) fails and causes the agent to die:

```ruby
      def read_file(file_path)
        content = ''
        File.open(file_path, 'r') do |file|
          read_chunk = Proc.new do
            content << file.read(options[:file_chunk_size])
            unless file.eof?
              EM.next_tick(read_chunk)
            else
              yield content
            end
          end
          read_chunk.call
        end
      end
```

The error is as follows:

```
/etc/sensu/extensions/client/system_profile.rb:76:in `read': closed stream (IOError)
	from /etc/sensu/extensions/client/system_profile.rb:76:in `block (2 levels) in read_file'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `block in run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `times'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/client.rb:12:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'
```

Apparently, the file (handle) is closed when the EM.next_tick is actually happening.

We worked around that by setting the file_chunk_size to 8192, but it'd be better to fix that nonetheless.  I'm afraid I don't spot the bug. :(

(An example file that is larger than 4k is [here](http://paste.openstack.org/show/AeqEjxh4G191rFzTD0uH/), although the error should be reproducible with a smaller file_chunk_size)

Cheers!
Stephan

**Comment by mattyjones** [comment]
@srenatus Is this still an issue that you would like help with?  If not I would like to close this in a at the end of the month.

Thanks

**Comment by srenatus** [comment]
@mattyjones I suspect the bug is still present, but I'm no longer concerned with that infrastructure, so... won't complain if you close it.

Cheers
