### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by yanntech** [sensu/sensu-community-plugins#513]
Hi,

I use sensu and plugins on AWS.
When I have few check particulary when plugins require fog/aws-sdk gem the load average on my instance is very high.

On my fork I try each time as possible to rewrite some part of plugin to handle many cloudwatch / rds / elasticache / etc ... Because the bottleneck is the load of external gem.

How is the best way to handle many check ? The good response is not "increase your instance type". I know I can dispatch checks to more instances but I think a better way can be found.

Regards,

**Comment by mattyjones** [comment]
@yanntech Is this still an issue that you would like help with?  If not I would like to close this in a at the end of the month.

Thanks

**Comment by yanntech** [comment]
Hi,

OK I close this issue
