### ISSUE TITLE
Using check-data with Graphite data

### ISSUE THREAD

**Issue by jagardaniel** [sensu/sensu-community-plugins#578]
Hello! 

I have a simple question about using Sensu to watch data from Graphite and using it for alerting. I'm using wmi_metrics.rb to throw data into Graphite from our Windows machines which works great. I was recommended to use the check-data plugin to watch those values. But this is the part I don't understand completely and I think the thing I'm asking for is a simple example how a check definition can look for the check-data plugin.

I guess you don't want to create a check definition for each server and for each value you want to check. Can you use it with wild cards and check many servers at the same time (***.domain.org.wmi.cpu.total.value) and then get the report back and be able to see which server that is causing the alert?

Thanks in advance
/Daniel

**Comment by mattyjones** [comment]
I will be closing this unless @joemiller, @jagardaniel, or @davidbirdsong have anything further they would like to add or a PR to submitted that is related to this issue
