### ISSUE TITLE
check-elb-health.rb : uninitialized constant RightAws::ElbInterface

### ISSUE THREAD

**Issue by frederic-jomedia** [sensu/sensu-community-plugins#586]
command ran (using sensu embedded ruby): check-elb-health.rb -a KEY -s SECRET  -r 'us-east-1' -n ELB_NAME

error : ELBHealth CRITICAL: An issue occured while communicating with the AWS EC2 API: uninitialized constant RightAws::ElbInterface

I have no problem with : check-elb-nodes.rb with the same KEY, SECRET and ELB_NAME

**Comment by mattyjones** [comment]
@frederic-jomedia  Is this still an issue that you would like help with?  If not I would like to close this in a at the end of the month.

Thanks

**Comment by bkett** [comment]
@frederic-jomedia Is there some reason you want to use the check that leverages right? I think this guy should be deprecated/removed in favor of the aws-sdk version ala check-elb-healh-sdk.rb

Let me know if that check is unsuitable for your needs.

**Comment by mattyjones** [comment]
@bkett :+1:

**Comment by frederic-jomedia** [comment]
@bkett I have not problem with a check using aws-sdk

**Comment by mattyjones** [comment]
@frederic-jomedia @bkett Let me know about this as well, I will pull the check from the [sensu-plugins-aws](https://github.com/sensu-plugins/sensu-plugins-aws) gem

**Comment by bkett** [comment]
@mattyjones The gem is available now?!?

**Comment by mattyjones** [comment]
Not yet, but the repo is live, I haven't tested the gemspec ir bundle yet
but I gaping that will drop by Monday.

**Comment by mattyjones** [comment]
@bkett [sensu-plugins-aws](https://rubygems.org/gems/sensu-plugins-aws)

Keep in mind this is still not prod grade.  I basicly cloned the repo as of a few hours ago and gave the readme and gemspec some bundler love, signed it and pushed it up.  For any further issues concerning AWS plugins and handlers please use the [new repo](https://github.com/sensu-plugins/sensu-plugins-aws)  Feel free to reference this issue.
