### ISSUE TITLE
Deprecate system/check-smart.rb in favor of smart/check-smart.rb

### ISSUE THREAD

**Issue by maoe** [sensu/sensu-community-plugins#632]
I think `plugins/smart/check-smart.rb` works better than `plugins/system/check-smart.rb` (and also `plugins/system/check-disk-health.sh`). As an author of `plugins/system/check-smart.rb`, I'd like to deprecate it in favor of `plugins/smart/check-smart.rb` because having multiple plugins which do the same thing may be confusing.

**Comment by mattyjones** [comment]
@maoe  I am going to close this issue but we are working on various solutions to this and in the very near future this should no longer be an issue.
