### ISSUE TITLE
check-ntp.rb doesn't handle loss of connection to NTP server

### ISSUE THREAD

**Issue by petere** [sensu/sensu-community-plugins#685]
`check-ntp.rb` checks the time offset against the currently selected peer.  If no remote peer is selected (because it lost the connection or none was configured), then ntp selects its local clock as peer, and `check-ntp.rb` will happily report a zero offset against its own system.

Because of that, this check isn't very robust and essentially useless for practical use.

**Comment by webmstr** [comment]
Or if you haven't yet configured the NTP server to check against, it seems to just check against the local time and report that everything is OK.
