### ISSUE TITLE
Newest check-procs.rb plugin breaks existing checks

### ISSUE THREAD

**Issue by jmreicha** [sensu/sensu-community-plugins#694]
I have Chef automatically pushing out the newest version of these scripts and the newest version of the `check-procs` plugin does not seem to be picking up checks correctly.  I verified by rolling this back and everything started working again.

**Comment by mattyjones** [comment]
The exit status error was not related to the original but instead stemmed from an issue with Rubocop that has since been corrected to my knowledge.
