### ISSUE TITLE
All AWS checks, etc should support IAM roles by default

### ISSUE THREAD

**Issue by shawnbutts** [sensu/sensu-community-plugins#707]
IAM roles are the AWS recommended way of assigning access tokens.

**Comment by bsnape** [comment]
I've found fog really easy to use for things I've built at my company. To use IAM roles I just do this:

```ruby
config = { region: 'eu-west-1',  use_iam_profile: true }
Fog::Compute::AWS.new(config)
```

Perhaps the official `aws-sdk` is just as easy to use but my uses are fairly limited (I just query instance names and IPs mainly).

**Comment by bkett** [comment]
@bsnape: I wasn't saying fog is bad, just that it's confusing and doesn't seem to add any additional functionality not already in the aws-sdk gem, and even if there is, it's certainly not being taken advantage of here. Thus the plugins have what I would call an extraneous dependency. The reason one wants to use fog is because you want cross-compatibility between cloud services. These plugins are specifically for AWS using AWS services (ELB, ElastiCache, etc.), and so there doesn't appear to be a compelling reason, at least in my eyes, why any of the AWS community plugins require fog. 

I'd also like to add the documentation for fog is pretty terrible compared to aws-sdk, the fog website doesn't even have a link to docs for aws specificially: http://fog.io/about/provider_documentation.html

**Comment by mattyjones** [comment]
@bkettb @bsnape  I tend to agree with this.  Unless you need the extra capability that fog brings I would think that the aws-sdk is the best tool for the job.  It will certainly be better maintained and integrated IMHO and that is worth the price of admission alone.

**Comment by bsnape** [comment]
Hey @bkett @mattyjones  I definitely hear what you're saying. I chipped in without really thinking about the point I was trying to make.

You're right, it's highly likely that `aws-sdk` is going to be updated in step with new AWS features as it's the official repo. That alone is probably a good enough reason to pick it.

Additionally, if there's one thing that `sensu-community-plugins` really needs it is sane dependency management, including only using one AWS API gem, or one HTTP gem etc. (or preferably use Ruby's built-in libraries where possible). Slightly off-topic but I would like to weigh in on dependency management/packaging discussions for this repo with what my company have done to package, deploy and run the checks from here. I've noticed the great work that @mattyjones has been doing on here recently so I'd like to help where I can.

**Comment by mattyjones** [comment]
@bsnape  Feel free to weigh in on the dep issue. 

<threadjack>
 I am a firm believer that the std lib should be the one used unless necessary specific functionality is desired.  I have no problem with random gems, but as we inch closer to a production grade release, I will be pinning all gems to a specific version and will start enforcing that.  If a new gem needs to be used it will need to bring something new to the party and a version will need to be pinned.

The reason for a lot of this headache is I have worked for several employers who will fight about using non-std gems and external packages on production systems.  The less we need to call and the more standard features we can leverage the easier a deployment can be presented to management.  Also the less gems I have to pin and manage on my systems the better as I leverage many of these on my production systems and I am very lazy ;)

There are many other reasons to standardize a gemset and most of us are aware of the issues for and against this.  Unfortunately, there is no way to compile ruby scripts into binaries like C and I think JRuby is not an option so we will just have to manage our dependencies as best we can.
</threadjack>

**Comment by runningman84** [comment]
Please use the native aws sdk. Fog just broke my knife installation :/

**Comment by mattyjones** [comment]
@runningman84 If you have the time could you either write some test for the aws plugins or do the refactor yourself?  I am somewhat tied up at the moment and I am very hesitant about making changes such as this without integration tests in place to confirm nothing gets broken.

Even though these should not be used  in a production environment many of us do and making a change such as this should be done very carefully.

**Comment by bkett** [comment]
@mattyjones I've already refactored everything to use aws-sdk, but I had no idea how to go about writing tests, any tips?

**Comment by mattyjones** [comment]
If you want to submit a PR, I would be more than happy to take a look at
them!

Concerning tests, take a look at the docs on RSpec3 and in the spec
directory a few have already been written.

**Comment by bkett** [comment]
@mattyjones I'll take a deeper look at those but a cursory glance doesn't show any examples for AWS, which has the extra challenges of interfacing with the AWS api I mentioned in my edited comment. Perhaps I'm overthinking the issue. 

Regardless I'll clean up the code, pull in any changes from head and make sure it conforms to the contribution guidelines before I submit the PR

**Comment by bkett** [comment]
My PR will also contain fixes allowing all checks to be run with an IAM role, which is the main reason for this issue existing. Figure I'll kill two birds with one stone.

**Comment by mattyjones** [comment]
That would be great, tests are not required yet so that is fine.  At some
point though all PR's for Ruby code will require tests ;). That won't
happen for a while, till at least all the current plugins have tests.

**Comment by bkett** [comment]
@mattyjones Alright pr made and passed travis checks (after many interations xD), let me know what your thoughts are.

**Comment by mattyjones** [comment]
Awesome!  I will tonight and if all is well merge soon!
