### ISSUE TITLE
Check failed to run: 500 "Internal Server Error"

### ISSUE THREAD

**Issue by jmreicha** [sensu/sensu-community-plugins#773]
I looked at [this issue](https://github.com/sensu/sensu-community-plugins/issues/697) first as it was using the same check, but it appears to be a different issue.  Sometimes when this check is run it will return 

    Check failed to run: 500 "Internal Server Error", ["/usr/lib/ruby/1.9.1/net/http.rb:2632:in `error!'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:143:in `request'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/rest.rb:115:in `get'", "/etc/sensu/plugins/check-chef-nodes.rb:52:in `block in nodes_last_seen'", "/etc/sensu/plugins/check-chef-nodes.rb:51:in `map'", "/etc/sensu/plugins/check-chef-nodes.rb:51:in `nodes_last_seen'", "/etc/sensu/plugins/check-chef-nodes.rb:77:in `any_node_stuck?'", "/etc/sensu/plugins/check-chef-nodes.rb:59:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-0.3.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

I can post more details just not sure what else is needed.

**Comment by mattyjones** [comment]
@jmreicha  Is this still an issue that you would like help with?  If not I would like to close this in a at the end of the month.

Thanks

**Comment by jmreicha** [comment]
@mattyjones sorry I didn't get back to you on this.  I honestly haven't looked at it in quite a while, you are good to close.
