### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by kalabiyau** [sensu/sensu-community-plugins#847]
- [ ] talk to @portertech about options and approaches:
 - [ ] centralized gem-like repo with all the gems-goodies + possible sensu - server installation
 - [ ] pros and cons of latter
 - [x] receive a green light
 - [ ] ...profit?

**Comment by miah** [comment]
I would avoid a doing a Opscode and making a Supermarket for 'gems'. Just package these checks as gems and put them on Rubygems. Make a site that lists things sure, but no reason to waste time/effort on building a new system. Its trivial to CI a Ruby Lib; example 

https://github.com/SimpleFinance/check_disk
https://rubygems.org/gems/check_disk
https://travis-ci.org/SimpleFinance/check_disk

**Comment by mattyjones** [comment]
I already have the beginnings of a gemspec written and I agree with the Travis CI thoughts @miah, though in the future I will be bringing the building and packaging into my employer's pipeline, **everything** will remain publicly accessible though .  I have a need/desire to do more testing than Travis will allow me such as testing against BSD, specific distro's etc.

**Comment by rhoml** [comment]
I like @miah idea also hubot's way works pretty fine.

**Comment by mattyjones** [comment]
@miah @rhoml   I am actually really liking hubot idea along with a few additional changes.  I will throw something together today and send it out but in a nutshell, I would break the plugins repo in many smaller repos organized by app.

* es plugins, handlers, etc
* windows plugins, handlers, etc
* core,hardware(system) plugins, handlers, etc
* etc

Then each of these would be their own gem that would could independently version.  If there was a major fix in aws we would only need to bump aws not the whole repo and a smaller subset of people would be affected.  This also lays the initial groundwork for plugins being called in an on-demand nature and allows for pinning of a version of each.  If box A is an ES box then I just add 'sensu-plugins-es' to a gemfile, cookbook, etc and only get what I want, not a ton of other cruft.

For those that want things the way they are we will create quarterly meta-gem releases of all the various gems, and these can be considered rock solid, whereas the individual gems could be considered production grade but active and the meta-gem would get built from each of these.  This paves the way for company's to create specific gemsets for only the software they run.  For example I run a lamp stack, I just create a meta-gem consisting of core, mysql, and apache.

Thoughts?

**Comment by rhoml** [comment]
+1 also each plugin could have separated tests.

**Comment by mattyjones** [comment]
@rhoml That would be another great thought.  It would make maintaining them much easier.  My only problem with this so far as I think about it is that dependency management would be moved to the plugin level instead at a higher level.

This is good because it will allow for less dependencies to be pulled into an environment but care would have to be taken as if multiple plugins got installed with dependencies at separate levels it would get annoying, to me at least.  In my mind everything needs to be pinned, so in that case you would just end up with version 1.4.1 and version 1.5.2 of a dependency and each plugin would use their respective version.

This could be somewhat solved over time as people build meta sets and such that all rely on a single version, as they pin their version and run the included integration tests if they pass then they could submit a PR back and we could bump the dependency for that specific gem.

**Comment by mattyjones** [comment]
[Sensu Packaging and Versioning RFC](https://gist.github.com/mattyjones/397e7bcc2fcc53f92842#file-sensu_pack_ver_rfc-md)

**Comment by mattyjones** [comment]
## Abstract
Packaging and versioning of the plugins is something I know a lot of people want and for good reason.  I would like to purpose a thought and see how people feel about it. In a nutshell I would like to split the community-plugins repo in smaller repos, based upon application.  This would mean all the Windows plugins, handlers, etc would go into a repo named **sensu-plugins-windows**, the aws ones would go to **sensu-plugins-aws** and so one. Some projects already do this to some extent, specifically Hubot, and it presents many advantages.

## Pros
* Application groups are easier to package and version than a monolithic repository
* Plugin groups could be installed by an automation tool or Sensu itself with ease and be dependent upon only those checks currently running
* There would be no need to bump the entire plugins repo for a small change to a single plugin
* A user could pin separate gem versions depending on their environment

## Cons
* More overhead concerning dependency management
* More jobs to create and manage
* Plugin groups may not work for everyone


For those that want things the way they are we will create quarterly meta-gem releases of all the various gems, and these can be considered stable, whereas the individual gems could be considered production grade but active and the meta-gem would get built from each of these. This paves the way for company's to create specific gemsets for only the software they run. For example a lamp stack meta-gem would consist of core(system), mysql, and apache.

Dependency management could be somewhat solved over time as the community builds custom meta sets and such that all rely on a single dependency version, as they pin their version and run the included integration tests, if they pass then they could submit a PR back and we could bump the dependency for that specific gem.
