### ISSUE TITLE
Google Summer of Code 2015

### ISSUE THREAD

**Issue by mattyjones** [sensu/sensu-community-plugins#865]
Project ideas: ?

* Build and release pipeline
* Complete testing infrastructure
* Possible RPM
* Gem
* Github.io Community Website

General Thoughts: ?

I was thinking of structuring the project as a not so much a feature driven project but more or a workflow driven project.  Find a student interested in release management and help us stabilize or improve the pipeline from it then current state. 

I was also thinking of a monitoring project, possibly combining the sensu-plugin and sensu-spec packages together into a framework that new checks could template or build off of.

@kalabiyau @portertech

**Comment by mattyjones** [comment]
@kalabiyau ^^

Thought on a GSoC project for a testing framework for the new repos.  There is one started [here](https://github.com/sensu/sensu-plugin-spec) and we can use it as a jumping off point but these repos need testing...

**Comment by kalabiyau** [comment]
@mattyjones I would like to have a student for packaging task. As we need to move it forward.

Not sure if we have more people willing to help with mentoring.

**Comment by kalabiyau** [comment]
@mattyjones let's hangout on IRC today about that matter

**Comment by mattyjones** [comment]
That would be great.  I would also like to touch base with you on packaging and such so we don't dupe effort and keep everything simple.  I will be in the office in about 90 minutes, we can talk then if you would like, otherwise I am available all day.

**Comment by kalabiyau** [comment]
Idea from `rob` 
I will ask @portertech about that matter
https://github.com/Yelp/sensu/issues/2
http://roobert.github.io/2015/01/08/Sensu-with-Host-Masquerading/
