### ISSUE TITLE
check-fstab-mounts.rb fails if using UUID for swap

### ISSUE THREAD

**Issue by melkore** [sensu/sensu-community-plugins#880]
The check fails when trying to find swap.  /proc/swaps shows swap being /dev/md0 which is a 4GB RAID1 partition.  That is the correct partition.

fstab:
UUID=ROOT-UUID /               btrfs   defaults,subvol=@ 0       1
UUID=SWAP-UUID swap	swap	sw	0	0
UUID=HOME-UUID /home           btrfs   defaults,subvol=@home 0       2

Error: 
Check failed to run: No such file or directory - /UUID=SWAP-UUID, 
[
"/etc/sensu/plugins/check-fstab-mounts.rb:48:in `realpath'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:48:in `realpath'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:48:in `block (2 levels) in check_mounts'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:48:in `select'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:48:in `block in check_mounts'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:37:in `each'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:37:in `check_mounts'", 
"/etc/sensu/plugins/check-fstab-mounts.rb:56:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"
]

**Comment by mattyjones** [comment]
@melkore I have toying with rewriting this check to make it cleaner and more streamlined.  At some point soon I will try and submit a PR for this.
