### ISSUE TITLE
open-uri vs. uri

### ISSUE THREAD

**Issue by mattyjones** [sensu/sensu-community-plugins#978]
open-uri is a wrapper for net/http, net/https, and uri where as uri is std library.  I would like to see us standardize on uri and not use wrapper gems as much unless there is a real need for them.  As we inch closer to a production grade release I would like to start limiting the gem count and relying on the std library whenever it makes sense to.

The following scripts use open-uri and would need to be rewritten:

* plugins/check-tripwire.rb:require 'open-uri'
* plugins/graphite/check-data.rb:#   gem: open-uri
* plugins/graphite/check-data.rb:require 'open-uri'
* plugins/solr/solr-v1.4graphite.rb:#   gem: open-uri
* plugins/solr/solr-v1.4graphite.rb:require 'open-uri'

There may be others, this was just a quick grep.

**Comment by jtimberman** [comment]
open-uri is in the ruby [standard library](http://www.ruby-doc.org/stdlib-2.2.0/libdoc/open-uri/rdoc/index.html). That links to 2.2.0, but it is in since before 1.8.7.

**Comment by mattyjones** [comment]
@jtimberman  I stand corrected :D.  The issue still stands that we should use only one of these.  Open-uri wraps a few other libs and IMHO seems to not be as full featured as URI so I still stand by my thoughts of favoring URI and refactoring out open-uri

**Comment by jtimberman** [comment]
I have looked into the various plugins here that use open-uri but I like using it in combination with URI.

[For example](https://github.com/jtimberman/vagrant-cookbook/blob/master/libraries/helpers.rb#L44):

```ruby
require 'open-uri'
require 'uri'

# ... later
sha256sums = open(URI.join(vagrant_base_uri, "#{vers}_SHA256SUMS?direct"))
```
