### ISSUE TITLE
rewrite all disk checks to use sys-filesystem for portability

### ISSUE THREAD

**Issue by mattyjones** [sensu/sensu-community-plugins#994]
https://github.com/djberg96/sys-filesystem

This gem may function as we need for disk check metrics and monitors.  I would like to explore using it as it will work across most *nix's and windows.

**Comment by mrichar1** [comment]
:+1:

**Comment by mattyjones** [comment]
@mrichar1 This is already partially implemented in the new repos.  I haven't had the cycles to circle back around to it though for a few weeks.
